// The multi-pod relay's pod-to-pod frame fan-out service (see
// docs/SPEC.md "Multi-pod relay: the peer transport"). The proto lives in
// the relay bounded context: the transport carries (app_slug, room_id,
// binary, data) and the frame body is OPAQUE to it - a durable mirror's
// seq rides inside data, an ephemeral frame has none - so the peer tier
// needs no schema knowledge and the envelope can evolve without touching
// this file.
//
// Regenerate with:
//
//	protoc --go_out=. --go_opt=paths=source_relative \
//	       --go-grpc_out=. --go-grpc_opt=paths=source_relative \
//	       roomrelay.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: roomrelay.proto

package relaygrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PublishRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The room's hub key: the app slug plus the room UUID.
	AppSlug string `protobuf:"bytes,1,opt,name=app_slug,json=appSlug,proto3" json:"app_slug,omitempty"`
	RoomId  string `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// The WebSocket message flavor the origin client used (text vs binary),
	// carried through so the receiving pod re-emits the same type.
	Binary bool `protobuf:"varint,3,opt,name=binary,proto3" json:"binary,omitempty"`
	// The opaque frame body, fanned out verbatim.
	Data          []byte `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishRequest) Reset() {
	*x = PublishRequest{}
	mi := &file_roomrelay_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRequest) ProtoMessage() {}

func (x *PublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_roomrelay_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRequest.ProtoReflect.Descriptor instead.
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return file_roomrelay_proto_rawDescGZIP(), []int{0}
}

func (x *PublishRequest) GetAppSlug() string {
	if x != nil {
		return x.AppSlug
	}
	return ""
}

func (x *PublishRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *PublishRequest) GetBinary() bool {
	if x != nil {
		return x.Binary
	}
	return false
}

func (x *PublishRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type PublishResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishResponse) Reset() {
	*x = PublishResponse{}
	mi := &file_roomrelay_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishResponse) ProtoMessage() {}

func (x *PublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_roomrelay_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishResponse.ProtoReflect.Descriptor instead.
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return file_roomrelay_proto_rawDescGZIP(), []int{1}
}

var File_roomrelay_proto protoreflect.FileDescriptor

const file_roomrelay_proto_rawDesc = "" +
	"\n" +
	"\x0froomrelay.proto\x12\x11hostthis.relay.v1\"p\n" +
	"\x0ePublishRequest\x12\x19\n" +
	"\bapp_slug\x18\x01 \x01(\tR\aappSlug\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12\x16\n" +
	"\x06binary\x18\x03 \x01(\bR\x06binary\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\"\x11\n" +
	"\x0fPublishResponse2]\n" +
	"\tRoomRelay\x12P\n" +
	"\aPublish\x12!.hostthis.relay.v1.PublishRequest\x1a\".hostthis.relay.v1.PublishResponseB4Z2github.com/Zamua/hostthis/internal/relay/relaygrpcb\x06proto3"

var (
	file_roomrelay_proto_rawDescOnce sync.Once
	file_roomrelay_proto_rawDescData []byte
)

func file_roomrelay_proto_rawDescGZIP() []byte {
	file_roomrelay_proto_rawDescOnce.Do(func() {
		file_roomrelay_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_roomrelay_proto_rawDesc), len(file_roomrelay_proto_rawDesc)))
	})
	return file_roomrelay_proto_rawDescData
}

var file_roomrelay_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_roomrelay_proto_goTypes = []any{
	(*PublishRequest)(nil),  // 0: hostthis.relay.v1.PublishRequest
	(*PublishResponse)(nil), // 1: hostthis.relay.v1.PublishResponse
}
var file_roomrelay_proto_depIdxs = []int32{
	0, // 0: hostthis.relay.v1.RoomRelay.Publish:input_type -> hostthis.relay.v1.PublishRequest
	1, // 1: hostthis.relay.v1.RoomRelay.Publish:output_type -> hostthis.relay.v1.PublishResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_roomrelay_proto_init() }
func file_roomrelay_proto_init() {
	if File_roomrelay_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_roomrelay_proto_rawDesc), len(file_roomrelay_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_roomrelay_proto_goTypes,
		DependencyIndexes: file_roomrelay_proto_depIdxs,
		MessageInfos:      file_roomrelay_proto_msgTypes,
	}.Build()
	File_roomrelay_proto = out.File
	file_roomrelay_proto_goTypes = nil
	file_roomrelay_proto_depIdxs = nil
}
