// The multi-pod relay's pod-to-pod frame fan-out service (see
// docs/SPEC.md "Multi-pod relay: the peer transport"). The proto lives in
// the relay bounded context: the transport carries (app_slug, room_id,
// binary, data) and the frame body is OPAQUE to it - a durable mirror's
// seq rides inside data, an ephemeral frame has none - so the peer tier
// needs no schema knowledge and the envelope can evolve without touching
// this file.
//
// Regenerate with:
//
//	protoc --go_out=. --go_opt=paths=source_relative \
//	       --go-grpc_out=. --go-grpc_opt=paths=source_relative \
//	       roomrelay.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: roomrelay.proto

package relaygrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RoomRelay_Publish_FullMethodName = "/hostthis.relay.v1.RoomRelay/Publish"
)

// RoomRelayClient is the client API for RoomRelay service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RoomRelay is the peer fan-out service every pod registers on the SAME
// cluster-internal gRPC server shale forwarding already runs. Best-effort:
// a peer that cannot be reached simply misses the frame (a durable
// mirror's loss is detectable at every affected subscriber via the dense
// seq; an ephemeral frame's loss is harmless by definition).
type RoomRelayClient interface {
	// Publish delivers one relay frame to this pod, which broadcasts it to
	// its own LOCAL subscribers of the room as server-originated. A received
	// frame is delivered locally only - never re-forwarded - so the origin
	// pod is the single fan-out point (full mesh, TTL 1) and no routing
	// loops exist by construction.
	Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error)
}

type roomRelayClient struct {
	cc grpc.ClientConnInterface
}

func NewRoomRelayClient(cc grpc.ClientConnInterface) RoomRelayClient {
	return &roomRelayClient{cc}
}

func (c *roomRelayClient) Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishResponse)
	err := c.cc.Invoke(ctx, RoomRelay_Publish_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RoomRelayServer is the server API for RoomRelay service.
// All implementations must embed UnimplementedRoomRelayServer
// for forward compatibility.
//
// RoomRelay is the peer fan-out service every pod registers on the SAME
// cluster-internal gRPC server shale forwarding already runs. Best-effort:
// a peer that cannot be reached simply misses the frame (a durable
// mirror's loss is detectable at every affected subscriber via the dense
// seq; an ephemeral frame's loss is harmless by definition).
type RoomRelayServer interface {
	// Publish delivers one relay frame to this pod, which broadcasts it to
	// its own LOCAL subscribers of the room as server-originated. A received
	// frame is delivered locally only - never re-forwarded - so the origin
	// pod is the single fan-out point (full mesh, TTL 1) and no routing
	// loops exist by construction.
	Publish(context.Context, *PublishRequest) (*PublishResponse, error)
	mustEmbedUnimplementedRoomRelayServer()
}

// UnimplementedRoomRelayServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRoomRelayServer struct{}

func (UnimplementedRoomRelayServer) Publish(context.Context, *PublishRequest) (*PublishResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Publish not implemented")
}
func (UnimplementedRoomRelayServer) mustEmbedUnimplementedRoomRelayServer() {}
func (UnimplementedRoomRelayServer) testEmbeddedByValue()                   {}

// UnsafeRoomRelayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RoomRelayServer will
// result in compilation errors.
type UnsafeRoomRelayServer interface {
	mustEmbedUnimplementedRoomRelayServer()
}

func RegisterRoomRelayServer(s grpc.ServiceRegistrar, srv RoomRelayServer) {
	// If the following call panics, it indicates UnimplementedRoomRelayServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RoomRelay_ServiceDesc, srv)
}

func _RoomRelay_Publish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomRelayServer).Publish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoomRelay_Publish_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomRelayServer).Publish(ctx, req.(*PublishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RoomRelay_ServiceDesc is the grpc.ServiceDesc for RoomRelay service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RoomRelay_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hostthis.relay.v1.RoomRelay",
	HandlerType: (*RoomRelayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Publish",
			Handler:    _RoomRelay_Publish_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "roomrelay.proto",
}
